// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: proto/server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UrlShortener_AddURL_FullMethodName      = "/grpc_server.UrlShortener/AddURL"
	UrlShortener_GetLongURL_FullMethodName  = "/grpc_server.UrlShortener/GetLongURL"
	UrlShortener_PostManyURL_FullMethodName = "/grpc_server.UrlShortener/PostManyURL"
)

// UrlShortenerClient is the client API for UrlShortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlShortenerClient interface {
	AddURL(ctx context.Context, in *LongURL, opts ...grpc.CallOption) (*ShortURL, error)
	GetLongURL(ctx context.Context, in *ShortURL, opts ...grpc.CallOption) (*LongURL, error)
	PostManyURL(ctx context.Context, in *PostManyURLRequest, opts ...grpc.CallOption) (*PostManyURLResponse, error)
}

type urlShortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlShortenerClient(cc grpc.ClientConnInterface) UrlShortenerClient {
	return &urlShortenerClient{cc}
}

func (c *urlShortenerClient) AddURL(ctx context.Context, in *LongURL, opts ...grpc.CallOption) (*ShortURL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortURL)
	err := c.cc.Invoke(ctx, UrlShortener_AddURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlShortenerClient) GetLongURL(ctx context.Context, in *ShortURL, opts ...grpc.CallOption) (*LongURL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LongURL)
	err := c.cc.Invoke(ctx, UrlShortener_GetLongURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlShortenerClient) PostManyURL(ctx context.Context, in *PostManyURLRequest, opts ...grpc.CallOption) (*PostManyURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostManyURLResponse)
	err := c.cc.Invoke(ctx, UrlShortener_PostManyURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlShortenerServer is the server API for UrlShortener service.
// All implementations must embed UnimplementedUrlShortenerServer
// for forward compatibility.
type UrlShortenerServer interface {
	AddURL(context.Context, *LongURL) (*ShortURL, error)
	GetLongURL(context.Context, *ShortURL) (*LongURL, error)
	PostManyURL(context.Context, *PostManyURLRequest) (*PostManyURLResponse, error)
	mustEmbedUnimplementedUrlShortenerServer()
}

// UnimplementedUrlShortenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUrlShortenerServer struct{}

func (UnimplementedUrlShortenerServer) AddURL(context.Context, *LongURL) (*ShortURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddURL not implemented")
}
func (UnimplementedUrlShortenerServer) GetLongURL(context.Context, *ShortURL) (*LongURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLongURL not implemented")
}
func (UnimplementedUrlShortenerServer) PostManyURL(context.Context, *PostManyURLRequest) (*PostManyURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostManyURL not implemented")
}
func (UnimplementedUrlShortenerServer) mustEmbedUnimplementedUrlShortenerServer() {}
func (UnimplementedUrlShortenerServer) testEmbeddedByValue()                      {}

// UnsafeUrlShortenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlShortenerServer will
// result in compilation errors.
type UnsafeUrlShortenerServer interface {
	mustEmbedUnimplementedUrlShortenerServer()
}

func RegisterUrlShortenerServer(s grpc.ServiceRegistrar, srv UrlShortenerServer) {
	// If the following call pancis, it indicates UnimplementedUrlShortenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UrlShortener_ServiceDesc, srv)
}

func _UrlShortener_AddURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LongURL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortenerServer).AddURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrlShortener_AddURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortenerServer).AddURL(ctx, req.(*LongURL))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlShortener_GetLongURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortenerServer).GetLongURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrlShortener_GetLongURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortenerServer).GetLongURL(ctx, req.(*ShortURL))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlShortener_PostManyURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostManyURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortenerServer).PostManyURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrlShortener_PostManyURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortenerServer).PostManyURL(ctx, req.(*PostManyURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UrlShortener_ServiceDesc is the grpc.ServiceDesc for UrlShortener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrlShortener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_server.UrlShortener",
	HandlerType: (*UrlShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddURL",
			Handler:    _UrlShortener_AddURL_Handler,
		},
		{
			MethodName: "GetLongURL",
			Handler:    _UrlShortener_GetLongURL_Handler,
		},
		{
			MethodName: "PostManyURL",
			Handler:    _UrlShortener_PostManyURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/server.proto",
}
